spring:
  application:
    name: order-service
  rabbitmq:
    host: 192.168.179.133
    port: 5672
    username: admin
<<<<<<< HEAD
    password: admin    
=======
    password: admin   
>>>>>>> branch 'master' of https://github.com/wenyi1840000/sp_repo.git
    
# server:
#  port: 8201
  
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202
